### ISSUE TITLE
Modificación del codigo para mostrar la desagregación del salario.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#11]
se ha requerido desagregar el monto del salario en la resolución, es decir esto aplica para los 4 tipos de resoluciones.
- [x] vinculación
- [x]  adición
- [x] reducción
- [ ] cancelación.

---

los items en los cuales se va a desagregar el valor son los siguientes:
- Sueldo básico
- prima de navidad.
- Prima de vacaciones.
- prima de servicios.
- aportes de cesantías de fondos públicos.

**Nota: para los docentes de honorarios y horas cátedra:  solo se toma su sueldo básico, es decir no se realiza des-agregación**

---

El equipo del proyecto Titan nos proveerá un servicio al cual apuntarle el cual  sequiere que se le envíen los siguientes parámetros:

- Salario.
- Año en que se realizo la Resolución.
- Fecha de inicio de la resolución.
- Fecha de Finalización de esta.

El api ya nos dará el valor desagregado.

***objetivos***

- [x] crear función en el cliente que permita enviar los paramentos y recibir la respuesta del Api.
- [x] modificar los pdf de tal manera ue se permita apreciar la visualización de esta des-agregación.

**Comment by BrayanB24** [comment]
Se inicia con el proceso de Modificación.

**Comment by BrayanB24** [comment]
La tabla que se plantea como posibilidad para la resolución de adición se muestra acontinuación: 
![2019-07-23](https://user-images.githubusercontent.com/45292226/61804696-f88d9100-adf9-11e9-987a-be859eda60ab.png)

Se procede con la modificación del código para llegar a esta tabla.

**Comment by BrayanB24** [comment]
Se termina con la generación de la tabla de desagregación para resolución de adición como se muestra en la imágen 
![image](https://user-images.githubusercontent.com/45292226/61904471-86e23f80-aeec-11e9-8404-b0bbf25e7929.png)
Se procede ahora con la segmentación de esta tabla para HCH, HCP y TCP-MTO

**Comment by BrayanB24** [comment]
El equipo de titan acaba de publicar el servicio solicitado como lo muestra el [issue 54](https://github.com/udistrital/titan_api_mid/issues/54) de titan_api_mid, una vez terminada la segmentación se procederá al ajuste de la respuesta para ser utilizado por el cliente.

**Comment by BrayanB24** [comment]
El servicio de Titan fue implementado, queda pendiente el rubro de "prima de servicios" que no está dentro del servicio, se continúa con la corrección de formato en los valores.

**Comment by BrayanB24** [comment]
Se termina con la corrección del formato de los valores de manera correcta, se muestran con el signo $ y la puntuación de miles. Se queda a la espera del valor de prima de servicios. Se continúa con la tabla de reducción.

**Comment by BrayanB24** [comment]
Las tablas en las resoluciones de reducción para HCP se muestran de manera correcta como lo muestra la siguiente captura: 
![image](https://user-images.githubusercontent.com/45292226/62094628-60513b00-b243-11e9-9979-cacc487b0c1c.png)
Hay que ajustar el valor con el cual se calcula la desagregación puesto que lo hace con el valor inicial del contrato y no con el valor final luego de hacer la reducción. Se espera que esto sea corregido en el MID.

**Comment by BrayanB24** [comment]
Se requieren que las tablas se modifiquen para que muestren los valores de desagregación faltantes y que la suma de exacta, se comienza con la modificación.

**Comment by BrayanB24** [comment]
Resolución de reducción terminada como sigue: 
![image](https://user-images.githubusercontent.com/45292226/62413556-e66bd980-b5d5-11e9-8f2e-9161ee650c3c.png)

**Comment by BrayanB24** [comment]
Se termina con las correcciones solicitadas, todos los pdf funcionando de manera correcta.

**Comment by BrayanB24** [comment]
Se corrigen las tablas de desagregación en las resoluciones dentro del módulo de modificaciones, también se corrigen los manejos de excepciones los cuales no permitían guardar modificaciones sobre las resoluciones, junto a esto se modifica también el formato del primer artículo permitiendo mostrar de manera correcta la generación de tablas.
