### ISSUE TITLE
Revisar la formula de redondeo del Ruler_api.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#12]
Validar la formula de Redondeo del Ruler_Api, puesto que al momento de pesarle los mismos parámetros para el calculo del contrato de un docente en ocasiones genera 1 peso mas, o 1 peso menos. 

***objetivos***
- [x] mandar varios datos repetidas veces para obtener un porcentaje de error promedio de la función
- [x] solicitar acceso a la función que realiza el redondeo. (en caso de ya tenerlo omitir este paso)
- [ ] proponer una función que remplace la actual o la corrija.
- [ ] realizar las mismas pruebas realizadas para la funciona antiguamente existente.
- [ ] implementar la nueva función en el cliente (esto en caso de que la función este fuera del cliente)

**Comment by anlramirezs11** [comment]
Se realizaron aproximadamente 200 pruebas apuntando al ADMINISTRATIVA_MID_SERVICE: "http://10.20.0.254/administrativa_mid_api/v1/ y en ninguna de las pruebas se presenta el error.

**Comment by anlramirezs11** [comment]
Informe miércoles: Debido a que no se presentó el error en local se procedió a hablar con Andrés; el me dice que el error pasa eventualmente y que va a revisar en la base de datos en producción donde se presentó. El queda pendiente de enviar datos para recrear el error en local.

**Comment by anlramirezs11** [comment]
Informe Jueves: Se despliega en local ADMINISTRATIVA_MID_SERVICE para revisar el servicio que devuelve el valor del contrato.

Se habla nueva mente con Andrés y el entrega datos del 2018 donde se presentó el error y confirma que, hasta la fecha, en la vigencia de resolución de 2019 no sea presentado el error; debido a esto se va a cambiar la vigencia de la resolución al 2018 e intentar recrear el error.

**Comment by anlramirezs11** [comment]
Informe Jueves: Después de realizar los cambios a nivel de código, se genera la resolución y los contratos no tuvieron una variación de un peso entre sí. 
Prueba 1- para profesores de proyecto curricular 79 (No se encontró el error)
![Prueba 1- para profesores de proyecto curricular 79](https://user-images.githubusercontent.com/29903400/61480184-00ad8280-a95b-11e9-98d0-caaaf2929a62.png)

**Comment by anlramirezs11** [comment]
Informe viernes: Se crea otra resolución y se encuentran a los docentes que el día anterior no se encontraba.  (79353298, 80497150, 79744401 y 80095218)

Se relizan pruebas con 3 de los docentes anteriores con una intensidad horaria semanal de 4 por 16 y a todos se les genera el mismo valor del contrato.
![Selección_004](https://user-images.githubusercontent.com/29903400/61553477-20f34500-aa20-11e9-9f03-0effdc02990a.png)

**Comment by anlramirezs11** [comment]
Conclusión: No se pudo encontrar el error apesar de que se simularon las condiciones en las que se presentó.  Las condiciones fueron: 
- Año de vigencia: 2018.
- Carga semanal: 4 horas.
- Semanas: 16.
- Dedicacación: HCP (2).

**Comment by anlramirezs11** [comment]
Se entraga documento donde se muestran las pruebas que se hicieron: 
https://docs.google.com/document/d/1gYEMB0qi-_Tjn7kcv40bN_w-4jX-kOBh24qvE7YUmYo/edit
