### ISSUE TITLE
Resoluciones debe permitir hacer mas de una modificación sobre las ya existentes.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#13]
Actualmente se presenta el problema de no poder realizar una modificacion sobre otra;es decir ; si a una resolución se le realiza una adicion , luego el sistema no permitira realizar una reduccion. Este problema debe ser solucionado.

***pasos a realizar***
- [ ] revisar como se realiza una modificación a una resolución y el flujo que esta sigue.
- [ ] revisar en la base de datos como se guarda una resolución y sus modificaciones.
- [ ] proponer una modificación (en caso de ser necesaria) para permitir la recursividad (se debe de tener en cuenta que ya hay datos en producción).
- [ ] en caso de modificar base de datos, producir el script de ALTER para esta.
- [ ] en caso de haber realizado modificación en la base de datos, escalar estas modificaciones a las respectivas apis.
- [ ] en el cliente se debe poder realizar una modificación sobre otra
- [ ] se debe de poder trear y mostrar los datos de la resolución original y sus modificaciones.

**Comment by jupmorenor** [comment]
Retomado en https://github.com/udistrital/resoluciones_docentes_crud/issues/7 y desarrollado dentro de https://github.com/udistrital/resoluciones_cliente_v2/issues/50, específicamente en el commit https://github.com/udistrital/resoluciones_mid_v2/commit/e6e5aa8fb925a77ae6906993356a78f1ce94f154
