### ISSUE TITLE
Ampliar filtro para consultar las resoluciones a las que se encuentra vinculado el docente.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#14]
Se requiere que el usuario pueda filtrar no solo por el numero de documento del docente, por ende se debe ampliar el filtro para que este tenga las siguientes 2 opciones extra de filtro:
- [ ] Vigencia de Resolucion
- [ ] Periodo de Carga.

---

Recomendaciones:
- si es posible tener un input o select con auto-completado, de no ser posible se sugieren las 2 siguientes opciones:
  - input con un ejemplo en el placeholder o Tooltip.
  - Select con las opciones disponibles.
- para mostrar los recomienda una tabla (en caso de que esta aun no este implementada.

**Comment by jupmorenor** [comment]
ver https://github.com/udistrital/resoluciones_docentes_crud/issues/10
