### ISSUE TITLE
Perfeccionar servicio que consulta saldo de un CDP.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#16]
El servicio que permite consultar el saldo de un CDP, debe perfeccionarse, puesto que resoluciones lo consulta, pero los datos no son acordes.

***objetivos***
*(en el cliente)*
- [x] revisar función de solicitud de CDP.
- [x] realizar pruebas para encontrar incoherencias o errores.
- [x] en el presente commit listar las inconsistencia s encontradas.
- [ ] solución de incoherencias.

*(en caso de ser lio del api informarlo en el presente issue y realizar los 4 objetivos anteriormente mencionados)*

**Comment by anlramirezs11** [comment]
Se debe confirmar que se valor se debe mostrar en el Saldo y como se halla. Ya me estoy comunicando con Miguel Ramírez para entender la lógica detrás del saldo del CDP

**Comment by jupmorenor** [comment]
En teoría es responsabilidad de Kronos, el desarrollo hecho en https://github.com/udistrital/plan_cuentas_mongo_crud/issues/253 contiene esta funcionalidad
