### ISSUE TITLE
Verificación de generación y modificaciones de actas de Resoluciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/resoluciones_cliente#4]
como proceso consecuente a lo mencionado en el issue #298 se requiere verificar si los pdf de resoluciones se generan correctamente con el fin de encontrar fallos y poder corregirlos. y tambien que se puedan editar cada una de las plantillas.

**Comment by anlramirezs11** [comment]
Se relizaron pruebas de la generación de pdf y el unico error que se encontró es que en el ultimo articulo (a veces el 8 o 7), no se pone la fecha de expedición de la resolución:
![Selección_006](https://user-images.githubusercontent.com/29903400/61559185-b8f82b00-aa2e-11e9-9d8d-9be0dd1b4820.png)

**Comment by BOTOOM** [comment]
yo diría que seria bueno realizar un checkout a las ramas en el estado anterior a la fusión pasa saber si eso ya estaba así o cambio con los merge.

si no me di a entender por favor comentar

**Comment by BrayanB24** [comment]
Para que la fecha de expedición aparezca de manera correcta la resolución aparte de ser generada debe ser también expedida, sin esto la fecha de expedición no aparecerá, confirmar si el error aparece también una vez expedida la resolución.

**Comment by anlramirezs11** [comment]
El error aparece una vez es expedida la resolución.

**Comment by anlramirezs11** [comment]
Se soluciona el error de null de en el pdf y csv en los docentes previnculados: 
![image](https://user-images.githubusercontent.com/29903400/61971223-29a9c500-afa4-11e9-8385-c1a3c922dd5f.png)

Había error con el símbolo $:
![image](https://user-images.githubusercontent.com/29903400/61974645-a80a6500-afac-11e9-92bb-324e47f2fadb.png)

**Comment by anlramirezs11** [comment]
Se arregla el articulo 1 de los pdf
![image](https://user-images.githubusercontent.com/29903400/62165925-23d61b80-b2e5-11e9-96ae-d1a5ae158967.png)

ya que antes no aparecía el número del contrato ni el año
