### ISSUE TITLE
Modificación de plantillas de resoluciones

### ISSUE THREAD

**Issue by BrayanB24** [udistrital/resoluciones_cliente#52]
Debido a que el usuario solicito cambios específicos en la plantilla sobre la tabla de las resoluciones DVE, se iniciara a realizar dichos cambios, empezando por dar a conocer una propuesta para mostrar los cambios que pide el usuario.

Luego de ello se comenzara a implementar en el cliente, el cambio se tendra que aplicar en los 4 formatos de resoluciones (Vinculación, adición, reducción y cancelación). 

En una primera fase de esta implementación se realizara con datos Dummy ya que las ecuaciones para los respectivos valores aun no se tienen

**Comment by BrayanB24** [comment]
Para este ajuste se comienza la revisión del estado actual de resoluciones DVE en preproducción.

**Comment by BrayanB24** [comment]
Se comienza con la modificación para la tabla de desagregación de las resoluciones de vinculación DVE, para esto se propone la siguiente tabla: 

![imagen](https://user-images.githubusercontent.com/45292226/67968708-df089c00-fbd5-11e9-8fc8-e992e9294843.png)

**Comment by BrayanB24** [comment]
Se deben revisar los path de configuración para los servicios del cliente, dado que todo se estaba manejando en el servidor 254 que dejo de funcionar hace algunos meses, se migrarán a los servicios de preproducción sin autenticación.

**Comment by BrayanB24** [comment]
Luego de hacer revisiones generales y solucionar el problema con la base de datos urano, se encuentra el obstáculo con el api de financiera_mid ya que no esta funcionando de manera correcta en la etapa de preproducción, pues este al tener que cargar los CDP no lo hace de manera correcta. Por tanto debe estudiarse la solución a implementar para lograr el funcionamiento correcto de la API.

**Comment by BrayanB24** [comment]
Se estudiará si el endpoint que consulta los CDP en el api mid de financiera hace algún registro de tipo POST para tener certeza de si realiza algún registro en alguna base de datos. Esto con el fin de poder utilizar este endpoint desde producción sin afectar con registros en dichas bases. De ser esto correcto se debe pedir aprobación para poder consultar de la base de producción y continuar con la modificación de las plantillas.

**Comment by BrayanB24** [comment]
Revizando el endpoint que realiza la consulta de los CDP en "financiera_mid" no parece existir alguna instrucción que realize una petición de tipo POST por lo que no debería afectar los datos de las tablas de producción, desde este endpoint no habrían problemas en cuanto afectaciones a datos de producción. Se debe ahora revisar la vista de resoluciones para comprobar de que no se haga POST en un paso siguiente del proceso de selección de CDP.

**Comment by BrayanB24** [comment]
Revisando la función que se ejecuta desde el cliente cuando se seleccionan los CDP no parece haber afectaciones directas a tablas relacionadas con financiera_mid por lo que no habrán modificaciones a las tablas de producción. Únicamente se realiza un POST a la api mid propia de resoluciones (administrativa_mid) por lo que se espera no tener afectaciones en producción. Se espera entonces la aprobación de consulta de tablas de producción por parte del arquitecto. 5

**Comment by BOTOOM** [comment]
para @BrayanB24 , en el presenta comentario de explicara los cambio que debe realizar para traer el cdp del crud en remplazo de utilizar el mid (del cual la funcionalidad del mid para esa petición es casi nula)

actualmente la funciona que se llama es la siguiente:

```javascript

self.actualizarLista = function (offset, query) {
            var req = financieraMidRequest.get('disponibilidad/ListaDisponibilidades/' + self.vigencia_data,
                $.param({
                    limit: self.Disponibilidades.paginationPageSize,
                    offset: offset,
                    query: typeof (query) === "string" ? query : query.join(","),
                    UnidadEjecutora: 1
                }));
            req.then(gridApiService.paginationFunc(self.Disponibilidades, offset));
            return req;
        };

```

siendo `financieraMidRequest` el servicio para pedir datos al mid, hare alucion a que las peticiones al crud son con `financieraRequest`, en caso de no ser asi en el ejemplo remplazar por la que es debida.

se recomienda remplazar la función de la siguiente manera

```javascript

self.actualizarLista = function (offset, query) {
            var unidadEjecutoraQuery = ",DisponibilidadApropiacion.Apropiacion.Rubro.UnidadEjecutora:" +1;
            var limitQuery ="&limit=" self.Disponibilidades.paginationPageSize;
            var offsetQuery ="&offset=" offset;
            var peticion = "query=vigencia:" +  self.vigencia_data + unidadEjecutoraQuery + limitQuery+ offsetQuery)
            var req = financieraRequest.get('disponibilidad?' + peticion;
            req.then(gridApiService.paginationFunc(self.Disponibilidades, offset));
            return req;
        };

```

con esto hago alusion a que ya le funcionara, la petición de prueba que se realizo en postman es la siguiente:

```
http://pruebasapi.intranetoas.udistrital.edu.co:8084/v1/disponibilidad?query=vigencia:2018,DisponibilidadApropiacion.Apropiacion.Rubro.UnidadEjecutora:1&limit=10
&offset=0
```

**Comment by BrayanB24** [comment]
Función modificada y ya selecciona los CDP correspondientes del API de financiera. Ya se dejan añadir docentes a las resoluciones.

**Comment by BrayanB24** [comment]
Se deben revisar bien los datos de los docentes ya que en algunos casos las resoluciones de HCP y TCO-MTO no muestran datos de docentes, se hará la revisión completa de los casos.

**Comment by BrayanB24** [comment]
Por otro lado hubo un cambio en el API de oikos y luego de una revisión de esa API se verifica que el endpoint no funciona correctamente y consultando con el equipo correspondiente dee utilizarse la V2 del mismo api. se procede con ello.

**Comment by BOTOOM** [comment]
esta tarea queda suspendida debido a el servicio de docentes que tiene información incompleta(el cual se esta resolviendo por parte del centro de servicios), adicional a esto faltan definir varios temas con el formato de la tabla y el servicio que se consumirá

**Comment by jupmorenor** [comment]
Se continua en el issue mencionado.
