### ISSUE TITLE
Corrección de los de docentes para las resoluciones

### ISSUE THREAD

**Issue by BrayanB24** [udistrital/resoluciones_cliente#54]
Para revisar la tabla de desagregación en las resoluciones es necesario que se puedan añadir docentes a las mismas. Este procedimiento no se ha podido llevar de manera correcta debido a que este servicio consultaba del antiguo servidor .254 por lo que hay que restaurar la carga de docentes en las resoluciones.

**Comment by BrayanB24** [comment]
Se plantean las posibilidades con el personal de soporte encargado del mantenimiento de la plataforma y se llega a la conclusión de que el procedimiento menos crítico a realizar es solicitar la sincronización de las bases de datos de producción con la de test, en el siguiente comentario estarán las bases de datos y sus respectivos esquemas a solicitar a los DBA. @BOTOOM

**Comment by BrayanB24** [comment]
Las bases de datos que se deben solicitar con sus respectivos esquemas se encuentran en el siguiente link, se queda a la espera de realizar la solicitud. 

https://docs.google.com/spreadsheets/d/1Ih7yET49TYIQOJY1Pjk_kWARYF7BxhJj0I3ocTuHfVA/edit?usp=sharing

**Comment by BOTOOM** [comment]
en el siguiente kamban se realiza la solicitud

https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34381

**Comment by BrayanB24** [comment]
Se revisa la carga de docentes apuntando a producción junto con @BOTOOM y se soluciona la carga docente. Se hace la modificación de la carga del supervisor en cada resolución dado que se detecta que los parámetros de consulta no existen actualmente. De la misma manera se detecta un error con el cálculo del salario de cada docente, no se encuentra el salario mínimo legal vigente de este año registrado lo que es necesario para el cálculo total, este mismo se debe solicitar mediante tuleap. @Eduargonzalez

**Comment by BrayanB24** [comment]
El salario minimo es ingresado correctamente en el sistema por el ingeniero encargado, se detecta un problema con la vigencia de la resolución la cual siempre toca el año en curso (en este caso 2020) por lo que no existen CDP correspondientes con esta vigencia, la recomendación es forzar (por ahora) la fecha 2019 en la creación de las resoluciones para que así se puedan escoger los CDP y continuar con el proceso.

**Comment by BrayanB24** [comment]
Se detecta el controlador en el mid el cual le asignaba el año correspondiente a cada resolución, este se modifica para que quede quemada el año 2019 para así lograr escoger los CDP. Ahora se detecta un problema con el almacenamiento de los docentes vinculados, por alguna razón los docentes no quedan en la resolución, eso mismo se revisará.

**Comment by BrayanB24** [comment]
Se comprueba el funcionamiento del modulo de resoluciones, logrando añadir docentes a las resoluciones y obteniendo los PDF correspondientes. Issue Terminada

**Comment by BOTOOM** [comment]
Para dar la tarea por aprobada se procederá a realizar el despliegue de los diferentes cambios y realizar pruebas en ambiente de test para cerrar completamente el issue.
