### ISSUE TITLE
Corrección del servicio de desagregación de salario para docentes en resoluciones.

### ISSUE THREAD

**Issue by BrayanB24** [udistrital/resoluciones_cliente#55]

**Comment by BrayanB24** [comment]
El servicio es corregido de manera correcta desde el controlador para la resolución de vinculación para docenes HCP , se debe validar para el resto de categorías y el resto de resoluciones.

**Comment by BrayanB24** [comment]
se valida funcionmiento en : 

- Resolución Vinculación docente HCP pregrado
- Resolución Vinculación docente HCP posgrado
- Resolución Vinculación docente TCO-MTO pregrado
- Resolución Vinculación docente HCH pregrado
- Resolución Vinculación docente HCH posgrado

**Comment by BrayanB24** [comment]
Para poder generar resoluciones de adición, reducción y cancelación se debe pasar por aprobación y expedición de las resoluciones anteriormente probadas y generadas.

**Comment by BrayanB24** [comment]
Se pueden aprobar de manera correcta las siguientes resoluciones de vinculación: 

- Resolución Vinculación docente HCP pregrado
- Resolución Vinculación docente HCP posgrado
- Resolución Vinculación docente TCO-MTO pregrado
- Resolución Vinculación docente HCH pregrado
- Resolución Vinculación docente HCH posgrado

**Comment by BrayanB24** [comment]
Se corrige la expedición de resoluciones, proceso necesario para crear las de adición reducción y cancelación. Se modifica endpoint correspondiente en el API de administrativa_mid_api

**Comment by BrayanB24** [comment]
Se expiden de manera correcta todas las resoluciones anteriormente mencionadas.

**Comment by BrayanB24** [comment]
se hace la modificación respectiva para cargar las resoluciones expedidas en el año "2019" por lo que se "quema" el valor del mismo en el cliente en el controlador resolución_generacion en la línea 109.

de la misma manera hay que recordar que las resoluciones se están generando también con año 2019 porque no existen CDP para 2020, esto debe corregirse una vez se quiera pasar a producción.

**Comment by BrayanB24** [comment]
Las resoluciones de reducción y cancelación no pueden ser generadas debido a que se necesita un RP asignado a los docentes. Por lo que se hará uso de resoluciones creadas anteriormente. 

- Para la resolución de reducción HCP Pregrado se utilizará la número 132
- Para la resolución de reducción HCP Posgrado no hay resolución que se pueda utilizar
- Para la resolución de reducción HCH Pregrado no hay resolución que se pueda utilizar
- Para la resolución de reducción HCH POSGRADO se utilizará la número 070
- Para la resolución de reducción TCO-MTO Pregrado no hay resolución que se pueda utilizar
- Para la resolución de reducción TCO-MTO Posgrado no hay resolución que se pueda utilizar

**Comment by BrayanB24** [comment]
Para las resoluciones de cancelación se utilizarán las siguientes: 

 

- Para la resolución de cancelación HCP Pregrado se utilizará la número 185
- Para la resolución de cancelación HCP Posgrado no hay resolución que se pueda utilizar
- Para la resolución de cancelación HCH Pregrado se utilizará la número 167
- Para la resolución de cancelación HCH POSGRADO no hay resolución que se pueda utilizar
- Para la resolución de cancelación TCO-MTO Pregrado no hay resolución que se pueda utilizar
- Para la resolución de cancelación TCO-MTO Posgrado no hay resolución que se pueda utilizar

**Comment by jupmorenor** [comment]
Se continúa en udistrital/resoluciones_cliente_v2#19
