### ISSUE TITLE
Apropiación de generalidades del sistema

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#61]
Documentos con información sobre las características del sistema
http://repository.udistrital.edu.co/bitstream/11349/6367/1/Rinc%C3%B3nCuracaMauricio2017.pdf

https://docs.google.com/document/d/1DB-HZ3O_ly0U0TxwF4iBg6tUUuGUBXpF2W7mfnR5PZY/edit

Sistema en preproducción de resoluciones
https://pruebasresoluciones.portaloas.udistrital.edu.co/#/
pruebasoas2
pruebasoas2

**Comment by anndresfelipe29** [comment]
- Gestión de resoluciones:
   - Resoluciones: 
      - No se carga ningún documento en la lista de resoluciones.
      - Al asignar profesores no carga ninguno (La razón se explica en el informe de estado final de resoluciones, tiene que ver con el tiempo de carga del api que trae la información).
      - Al consultar un docente solo muestra una lista de resoluciones sin poder ver otra información del docente. 
   - Generar resolución: No cargan las facultades  en las resoluciones por vinculación, 
- Administración de resoluciones:
   - No se puede ver la información de las resoluciones (Al parecer apunta a un servicio local)
- Reportes Resoluciones:
   - No permite elegir facultad, y esto impide el envió del formulario
- Generar solicitud de registro presupuestal:
   -  No funciona la búsqueda de CDP.
   -  No funciona la búsqueda por resolución.
   - Búsqueda por contrato:
     - Se generan errores de apis al solicitar RP, generando que no cargue información en selección CDP y tampoco en selección de compromiso.
