### ISSUE TITLE
Eliminación de tabla de desagregación

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#63]
- [x] Resoluciones tipo vinculación
- [x] Resoluciones tipo adición
- [x] Resoluciones tipo reducción
- [x] Resoluciones tipo cancelación

**Comment by anndresfelipe29** [comment]
a3cbd91ffbb5ce98400e06019a73b01da04b3020

**Comment by anndresfelipe29** [comment]
Ahora se pueden ver las los cuatro tipos de resolución, ya no usan el servicio de desagregación y cargan con la tabla anterior.
Commit en el cual se suben los cambios a3cbd91ffbb5ce98400e06019a73b01da04b3020 .
