### ISSUE TITLE
Validación de funcionalidades del sistema

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#64]
Validar las siguiente funcionalidades del sistema que pueden estar fallando:

- [ ] Mostrar docentes
- [x] Mostrar facultades
- [x] Mostrar tabla con la información desagregada del sueldo de los docentes
- [ ] Endpoint de nuxeo, error al cargar documentos expedidos. 22/10/2020
- [ ] Error al generar resoluciones. 22/10/2020

**Comment by anndresfelipe29** [comment]
Se evidenciaba que no cargaban las facultades en  las vistas de Generar resolución y Reportes Resoluciones, esto  impedía completar algunos formularios. Se corrige el problema alterando la petición https://autenticacion.portaloas.udistrital.edu.co/apioas/oikos_crud_api/v1/dependencia_tipo_dependencia/?query=TipoDependenciaId.Id%3A2&fields=DependenciaId&limit=-1

Donde se elimina el filtro de campo de la consulta y ahora se hace desde el front end.
Esta solución permite la visualización de la información de facultad y el envió del formulario, permitiendo apreciar nuevos errores al enviar el formulario de generar resolución.

**Comment by anndresfelipe29** [comment]
Se retoma el trabajo con resoluciones, encontrando que:
- Vista Gestión de resoluciones:
  - No se pueden visualizar algunos de los documentos expedidos.
  
![image](https://user-images.githubusercontent.com/30865375/104780312-92fc3580-574e-11eb-8261-0d106624bb5a.png)

  - Al descargar una resolución se ve mal el titulo.
  
![image](https://user-images.githubusercontent.com/30865375/104780358-aa3b2300-574e-11eb-8367-7b35d62a562d.png)

  - No se pueden crear nuevas resoluciones, se queda cargando el aplicativo.
  
![image](https://user-images.githubusercontent.com/30865375/104780416-c4750100-574e-11eb-98d7-c90c423a9513.png)

  - Al asignar profesores no carga ninguno (La razón se explica en el informe de estado final de resoluciones, tiene que ver con el tiempo de carga del api que trae la información https://docs.google.com/document/d/1DB-HZ3O_ly0U0TxwF4iBg6tUUuGUBXpF2W7mfnR5PZY/edit ).
  - No se pueden expedir resoluciones, el proceso en el cliente es correcto y se muestra correcto pero no cambia el estado de la resolución.

**Comment by ddguerra90** [comment]
Se cierra el issue ya que se procede con un nuevo plan de trabajo
https://docs.google.com/document/d/1F5z1moMMML6EryM5PEztMOdt5kukKpgd1qq--51dlys/edit#heading=h.gjdgxs
