### ISSUE TITLE
Consulta y expedición de documentos en nuxeo

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#65]
- [x] Creación de resoluciones
- [x] Consulta de resoluciones

**Comment by anndresfelipe29** [comment]
Se revisa la vista de administración de resoluciones y se arregla desde el front-end los errores que no permitian expedir una resolución, ahora el front-end puede expedir resoluciones sin error ( b4973b4f515fe660b1522c4cb8048e0337710bd8) , pero el servicio back-end correspondiente a esta operación falla.

Se revisa el servicio back-end administrativa_mid_api en la petición post expedir_resolución y se encuentran algunos fallos pero al parecer son por falta de datos en otras apis. Para estar seguros que es un fallo por falta de datos, se debe crear una resolusión desde cero y para eso se deben corregir otros errores.

**Comment by jupmorenor** [comment]
Desarrollado en https://github.com/udistrital/resoluciones_cliente_v2/issues/13
