### ISSUE TITLE
Viabilidad e independización del sistema

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#68]
Revisar que se utiliza por parte del cliente, que apis y que tablas esta utilizando para planear una independización del sistema, de tal manera que se pueda crear un mid y un crud específico para resoluciones.

**Comment by anndresfelipe29** [comment]
Se realiza un análisis completo sobre la viabilidad de independizar el aplicativo de resoluciones del las api de administrativa. 
https://docs.google.com/document/d/1F5z1moMMML6EryM5PEztMOdt5kukKpgd1qq--51dlys/edit
[Resoluciones.pdf](https://github.com/udistrital/resoluciones_cliente/files/5823009/Resoluciones.pdf)
