### ISSUE TITLE
Revisión modelo de la base de datos

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/resoluciones_cliente#69]
Revisar el modelo de la base de datos y contrastarlo con los lineamientos definidos por la OAS

**Comment by anndresfelipe29** [comment]
Con el analisis de inicio se encuentra documentado el siguiente  esquema para el aplicativo de resoluciones:
![modelo_resoluciones (2)](https://user-images.githubusercontent.com/30865375/104958353-db5d6280-599d-11eb-8d65-1f14aaec4090.png)

Al revisar el codigo del sistema, se encuentra además que existen otras tablas que pueden hacer parte del esquema resoluciones, las tablas involucradas son:
- resolucion_estado,  
- estado_resolucion  
- componente_resolucion

**Comment by anndresfelipe29** [comment]
Se aplican correcciones al esquema existente a partir de las tablas que se encuentran en preproduccion y los lineamientos obteniendo : 
![resoluciones](https://user-images.githubusercontent.com/30865375/104977446-8e918000-59cd-11eb-9104-f59a7430db27.png)

Se solicita revision por parte de los dba @fnrojash  y @nodier25

**Comment by blacburn** [comment]
Buen día, 
 
De acuerdo a lo indicado en la reunión de revisión, de indica lo siguiente:

- Se debe realizar la eliminación del campo **estado** en la tabla **resoluciones** y **vinculacion_docente** , ya que se manejaria el estado del registro a través del campo **activo**.
- El campo **objeto** de la tabla resolución, se valida en producción donde siempre es nulo dicho campo, por lo tanto se solicita realizar la eliminación en el nuevo modelo del mismo.
- El campo **usuario** de la tabla resolucion_estado, se debe dejar traza del usuario quien realiza el cambio de estado en el nuevo desarrollo.
- El modelo se proyectá será creado en la base de datos udistrital_administrativa, en el schema resoluciones.

Muchas gracias.
