### ISSUE TITLE
Actualización de plantillas de las resoluciones.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/resoluciones_cliente#70]
Ajustar formato de las resoluciones de pregrado y postgrado para el periodo 2020 de acuerdo al modelo enviado por soporte o el consultado en los comments realizado por parte de ellos.

Ejemplo fase anterior : https://github.com/udistrital/resoluciones_cliente/issues/41

**Comment by jupmorenor** [comment]
Desarrollado en https://github.com/udistrital/resoluciones_mid_v2/issues/1
