### ISSUE TITLE
Introducción al sistema de Resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#74]
Asimilar el funcionamiento general del sistema así como de su flujo y actividades necesarias por desarrollar, de acuerdo a las siguientes actividades:
 
- [x] Revisión e instalación de repositorios (Crud, Mid y Cliente).
- [x] Revisión de documentación.
- [x] Análisis de requerimientos.

**Criterios de aceptación**

1. Registrar el estado actual en el que se recibe el sistema (Formato propio).
2. Registrar inquietudes respecto a los requerimientos analizados.

**Comment by a52290451** [comment]
Comparto documento de [Oportunidades de mejora a los sistemas de la OAS](https://docs.google.com/spreadsheets/d/1cjopqv5tNE1EEQ0abhySsmPuoA20e-vzqgmYk7Wr_ek/edit?usp=sharing) en donde se profundiza en las especificaciones de cada requerimiento.

**Comment by jupmorenor** [comment]
Se recibe el sistema de Resoluciones que consta de tres componentes de software:

1.	resoluciones_docentes_crud
2.	resoluciones_docentes_mid
3.	resoluciones_cliente

Este sistema se encuentra en proceso de aislamiento ya que anteriormente estos componentes hacían parte de otro sistema en forma de módulos.
Para cada uno de estos componentes se encuentra lo siguiente:

1.	El componente resoluciones_docentes_crud se encuentra terminado con su respectivo modelo de datos y con despliegue activo en ambiente de pruebas con el endpoint http://pruebasapi2.intranetoas.udistrital.edu.co:8516, aunque este endpoint no se ha podido probar directamente por falta de VPN se cuenta también con la url de autenticación (obtenida del inventario de APIs), en este caso se obtiene la siguiente respuesta con el usuario pruebasoas2 que se venía usando en este sistema, probablemente no cuente con los permisos necesarios o exista un problema en la configuración de la API en el sistema de autenticación: 

```
<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
    <ams:code>900908</ams:code>
    <ams:message>Resource forbidden </ams:message>
    <ams:description>Access failure for API: /resoluciones_docentes_crud/v1, version: v1 status: (900908) - Resource forbidden </ams:description>
</ams:fault>
```

2.	El componente resoluciones_docentes_mid contiene 6 controladores y las respectivas funciones helpers y estructuras de datos de uso interno, los controladores son:

- gestion_resoluciones
- gestion_desvinculaciones
- gestion_previnculaciones
- gestion_documento_resolucion
- expedir_resolucion

Al parecer esta nueva API MID también se encuentra lista y desplegada en ambiente de pruebas, pero esto no se ha podido verificar todavía, en el inventario de APIs no se encuentran relacionados los enlaces correspondientes. (ver udistrital/resoluciones_docentes_mid#8)

3.	El componente resoluciones_cliente es un clon de administrativa_cliente del que se debe dejar únicamente la parte correspondiente a resoluciones. Al revisar el código se identifican los componentes de software correspondientes, donde se evidencia que usa las APIs correspondientes al sistema Administrativa. Al usar el sistema no se encuentran opciones de menú para acceder al módulo de resoluciones, pero se pueden usar las rutas encontradas en el código que presentan errores.

**Comment by jupmorenor** [comment]
Se valida el estado de los kanban relacionados en udistrital/resoluciones_docentes_mid#8 correspondientes a las solicitudes de despliegue, se encuentra que el componente resoluciones_docentes_mid finalmente NO fué desplegado en ambiente de pruebas.
