### ISSUE TITLE
Propuesta del plan de trabajo (Independizar sistema y estabilizar)

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#75]
Proponer el plan de trabajo para cubrir los requerimientos de optimización del sistema relacionados con las tareas necesarias para independizarlo y estabilizarlo.

**Nota**:
Se debe tomar en consideración la [validación del estado actual del sistema](https://github.com/udistrital/resoluciones_cliente/issues/76) y el análisis de requerimientos realizado en [Introducción al sistema de Resoluciones](https://github.com/udistrital/resoluciones_cliente/issues/74).

De igual forma, se debe asignar prioridad y un estimado de tiempo a cada item.

**Criterios de aceptación**

- [ ] Documento con la propuesta de trabajo realizada (Formato del documento libre).

**Comment by jupmorenor** [comment]
Adjunto enlace a documento propuesta de plan de trabajo: https://drive.google.com/file/d/10uq6sh52p1oLimxUuZEUbB_tfyAYFzZL/view?usp=sharing

**Comment by jupmorenor** [comment]
Se ha actualizado el documento del plan de trabajo, el enlace es el mismo
