### ISSUE TITLE
Validar estado del sistema (Diagnostico)

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#76]
Se debe realizar el diagnostico del sistema, con base en el plan de trabajo dispuesto en [Viabilidad e independización del sistema](https://github.com/udistrital/resoluciones_cliente/issues/68) y los demás Issues relacionados.

**Criterios de aceptación**

- [x] Documento en donde se especifique el estado en el cual se recibe el sistema, las tareas realizadas en fases anteriores y las que faltan por realizar para terminar el proceso de independización del sistema.

**Comment by jupmorenor** [comment]
Se realiza análisis detallado de cada componente del sistema (CRUD, MID y cliente) y se genera el siguiente documento con las observaciones correspondientes a cada uno: 
https://drive.google.com/file/d/1IIqH0299BIzX-UKsHxrQSQFcOexpqAg0/view?usp=sharing
