### ISSUE TITLE
Emparejar desarrollo en resoluciones con administrativa cliente

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#77]
De acuerdo a los cambios realizados en Administrativa cliente en cuanto a resoluciones, se debe realizar el emparejamiento de ambos sistemas, cumpliendo las tareas que sean necesarias.

**Criterio de aceptación**

- [x] Ajuste de resoluciones y commit en rama feature.

**Comment by jupmorenor** [comment]
Se realiza la actualización del cliente con respecto a su original administrativa_cliente en cuanto a los cambios que se han realizado desde que comenzó el proceso de independización. Al observar las fechas se identifica que se requiere recuperar lso cambios desde el commit [d65bd05](https://github.com/udistrital/administrativa_cliente/commit/d65bd05312d3d6a0d25cceebab58ced5075f6be2) hasta el commit mas reciente que es [af0c548](https://github.com/udistrital/administrativa_cliente/commit/af0c54841ea1ceccf05ea107cdb46980850011f4) en la rama [resoluciones](https://github.com/udistrital/administrativa_cliente/tree/resoluciones) de ese repositorio.
