### ISSUE TITLE
Pruebas Funcionales y de Usabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#78]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la independización del sistema de resoluciones.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

Nota: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634) dispuesto para la aplicación de este tipo de pruebas.

**Comment by jupmorenor** [comment]
Se realiza una primera aplicación de pruebas funcionales en entorno de preproducción, se identifican 5 fallas importantes: 
[Documento de pruebas funcionales](https://docs.google.com/spreadsheets/d/1IcpCmD6ie285WC4c4FtsweHSJAJ_3KCV/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

**Comment by jupmorenor** [comment]
Se ha dado solución a varias de las fallas detectadas en las pruebas funcionales de la siguiente manera:

1. Se actualizan las variables de entorno por medio del kanban [43719](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=43719), con esto se ha garantizado el acceso a la información en el ambiente de pruebas
2. Se han actualizado los esquemas de datos de Kronos, Argo y Agora de los que depende el sistema.
4. Se ha garantizado a Resoluciones el acceso a las apis financiera_crud_api y financiera_mid_api
