### ISSUE TITLE
Pruebas de carga y seguridad

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#79]
Solicitar con anticipación las pruebas de carga y seguridad correspondientes al desarrollo realizado para la independización del sistema.

**Criterio de aceptación**

- [x] Documento con los resultados de las pruebas aplicadas.

**Comment by a52290451** [comment]
Los resultados se presentan a continuación:
- [Evaluación de vulnerabilidades](https://docs.google.com/document/d/16n6Pr7MjNUKFfIv8kLFhQa4HcZO18hbPu3ALlEc4ABk/edit?usp=sharing)
- [Evaluación de vulnerabilidades en código fuente](https://docs.google.com/document/d/1qj2_NtU1szLbPv_YNUle7I4t8w4HJNCtnpvRh0_hgTY/edit?usp=sharing)
- [Observaciones](https://docs.google.com/document/d/1cGP9_CaRXYXGxj2PPdNNIEafc0ZN1rMBM8Fr4GuD0u0/edit?usp=sharing)

**Comment by jupmorenor** [comment]
Se aplicaron correcciones al sistema de acuerdo a los resultados de las pruebas, el detalle se encuentra en el siguiente documento:

https://docs.google.com/document/d/14PywppNevHAN0-JGKEeq2UHW1USNpETN/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true
