### ISSUE TITLE
Estructura de Módulos para nuevo Resoluciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#90]
Anexar estructura de módulos para nuevo resoluciones. Considerar conexiones necesarias a nivel interno y con otros sistemas, además del flujo de procesos o tareas especificas a implementar.

**Criterio de aceptación**

- [x] #93

**Comment by jupmorenor** [comment]
Se realiza análisis de módulos y conexiones con otros sistemas detallando el flujo de los procesos a través de estos módulos en un diagrama de componentes:
![resoluciones diagrama](https://user-images.githubusercontent.com/11802554/133542759-1e4be537-bff5-4653-a40e-8d728f21cbaa.png)

**Comment by jupmorenor** [comment]
Se desarrolla un diagrama de actividades que muestra el flujo de los procesos en el sistema de resoluciones.
![Resoluciones actividades](https://user-images.githubusercontent.com/11802554/133710935-f8204b40-7ff6-446d-b0b2-baf8ae7ed412.png)

**Comment by a52290451** [comment]
Diagrama pendiente a validación: @Eduargonzalez

**Comment by Eduargonzalez** [comment]
Contempla el flujo macro de lo que sería el sistema de resoluciones, donde podemos identificar las funcionalidades esenciales que tendría y que cubriría. Para una primera versión esta bien, pero si seria necesario alimentarlo conforme a como se vaya analizando el sistema, desagregando en cada una de las transacciones ( Vinculación, Adición, Reducción, Cancelación) el como se lleva a cabo cada una de ellas ( Información necesaria ). También para ir mencionando con que sistemas vamos a interoperar.

**Comment by jupmorenor** [comment]
Se agregan actividades relacionadas con las plantillas. El detalle de las transacciones para cada tipo de resolución se obtendrá a partir del análisis de las historias de usuario y creo que por conveniencia es mejor desarrollarlos en diagramas separados.

![Resoluciones actividades](https://user-images.githubusercontent.com/11802554/134062365-4c882d2b-25fc-47ca-a88c-0173c07f3944.png)
