### ISSUE TITLE
Creación de historias de usuarios para nuevo resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#94]
Se requiere realizar la creación de historias de usuario para el nuevo sistema de resoluciones teniendo en cuenta los módulos y funcionalidades que se deben abordar.

**Criterio de aceptación**

- [x] Historias de usuario resultado del análisis de funcionalidades requeridas en cada módulo.

**Nota**: tomar en consideración la [Estructura de Módulos para nuevo Resoluciones](https://github.com/udistrital/resoluciones_cliente/issues/90) y el [formato](https://docs.google.com/spreadsheets/d/17LVcBS_MZrG_notBSaOBFRZNMmQ5UvdX/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true) dispuesto para historias de usuario.

**Comment by jupmorenor** [comment]
Se elabora [documento con historias de usuario](https://docs.google.com/spreadsheets/d/1RFiEqzjsTLb7OO0b73C_noPe8XlxnCnb/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true) para el nuevo sistema de resoluciones

**Comment by a52290451** [comment]
Resultado de la revisión de historias de usuario:

1. Es importante señalar el rol de usuario implicado en cada HU. 
2. En rojo se mencionan las sugerencias o correcciones a realizar.
3. Se requiere completar las HU faltantes.

**Comment by a52290451** [comment]
Se solicita a @Eduargonzalez realizar una segunda revisión sobre el documente presentado por @jupmorenor

**Comment by jupmorenor** [comment]
Se realizó actualización del documento asi:
1. Se han agregado los roles basados en los que el sistema Argo tenía asignados para la parte de Resoluciones.
2. Se realizaron las correcciones indicadas.
3. Se completaron las HU que estaban sin terminar y se agrega una historia nueva.

**Comment by Eduargonzalez** [comment]
Para la funcionalidad de reportes se tiene que tener en cuenta que información va necesitar la sección de presupuesto, en este reporte se debe mostrar el desagregado del salario total del docente. 

A parte de los reportes veo que ya están completas las funcionalidades y Conforme al diligenciamiento del formato para las HU´s.
