### ISSUE TITLE
Análisis preliminar - Nuevo resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente#99]
Realizar el análisis preliminar de componentes y endpoints necesarios a implementar y utilizar en el nuevo sistema de resoluciones.

**Criterios de aceptación**

- [x] Documentación relacionada con el análisis realizado.

**Comment by jupmorenor** [comment]
Se elabora una tabla que relaciona las diferentes APIs a las que se conecta el sistema de Resoluciones, esto con el fin de evaluar la pertinencia de cada una y buscar alternativas cuando sea necesario para el sistema nuevo. 

[Enlace al documento](https://docs.google.com/spreadsheets/d/1oQ48wzCJZtPQLXsvFY8KPlIYzIFviLBX/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)
